migrate to node:test with c8
fastify/fastify-formbody pull request #161
Opened 2024-09-09 07:16 UTC by narendra-reddy-nf

This PR replaces tap with node:test and introduces c8 for code coverage.

# Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-09-09 07:18 UTC, gurgunday commented on package.json
> +    "test:unit": "c8 node --test",
```suggestion
    "test:unit": "c8 --100 node --test",
```

2024-09-09 07:18 UTC, gurgunday commented on package.json
> +    "c8": "^7.12.0",
why v7?

2024-09-09 07:21 UTC, mcollina approved these changes
lgtm

2024-09-09 08:29 UTC, Uzlopak requested changes
t.plan exists on node 20 and 22
https://nodejs.org/api/test.html#contextplancount

2024-09-11 08:21 UTC, simoneb requested changes

2024-09-11 08:21 UTC, simoneb commented on test/integration.test.js
>    t.plan(3)
with the change that you did below, using t.plan is no longer necessary

2024-09-11 08:21 UTC, simoneb commented on test/integration.test.js
>    t.plan(3)
same as before

2024-09-11 11:15 UTC, simoneb approved these changes

2024-09-11 11:29 UTC, gurgunday approved these changes
lgtm

2024-09-11 11:32 UTC, merged